env:
  node: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
globals:
  log: true
  error: true
  success: true
  warn: true
  info: true
  process: true
  it: true
  describe: true
  fs: true
  sysPath: true
  async: true
  childProcess: true
  leftPad: true
  rightPad: true
  globby: true
  optimist: true
  loaderUtils: true
  extend: true
  yaml: true
  requireUncached: true
  mkdirp: true
  JSON5: true
  YKIT_COMMANDS_PATH: true
  YKIT_RC: true
  USER_HOME: true
